### PR TITLE
dependency bump

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@benbp as you asked, here are the updated revs from last I tested.

adding a few others for review

@rolandpoulter 
@tldavies

### CODE REVIEW

**Comment by benbp** [comment]
Thanks :+1:

**Comment by heckj** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
@benbp fixed all new dependency issues and I think this is ready to be merged.

**Comment by DavidjohnBlodgett** [comment]
@RackHD/corecommitters expanding the audience.

**Comment by anhou** [comment]
:+1:

**Pull request merged**
