### PR TITLE
Update Vagrantfile to get the newest version of ansible and run build_all script

### PR DESCRIPTION
**Pull request by tldavies**

### CODE REVIEW

**Comment by tldavies** [comment]
@DavidjohnBlodgett

**Comment by heckj** [comment]
:+1:

**Comment by tldavies** [comment]
@RackHD/corecommitters

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
