### PR TITLE
build monorail.intel.ipxe

### PR DESCRIPTION
**Pull request by heckj**
resolves https://github.com/RackHD/RackHD/issues/345

### CODE REVIEW

**Comment by heckj** [comment]
@codenrhoden FYI

**Comment by heckj** [comment]
(verified locally for file generation, separate update needed for ansible/scripting to grab the relevant files - https://github.com/RackHD/RackHD/pull/349)

**Comment by heckj** [comment]
@RackHD/corecommitters please review

**Comment by benbp** [comment]
👍

**Comment by anhou** [comment]
:+1:

**Pull request merged**
