### PR TITLE
Adds Vagrantfile and fixes curl version

### PR DESCRIPTION
**Pull request by rolandpoulter**
@benbp

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by iceiilin** [comment]
+1

**Comment by iceiilin** [comment]
I like the idea of using vagrant to build images. The readme might be updated as well.

**Comment by benbp** [comment]
@rolandpoulter yeah, will you add a quick README blurb about spinning up Vagrant? Then I'll merge.

**Comment by rolandpoulter** [comment]
@benbp Honestly I added the Vagrantfile before I knew I could download the files from bintray. I know `vagrant up` works and it runs ansible, but I didn't get passed that. So I don't know if it actually builds the files or how to get them out of the vm.

**Pull request merged**
