### PR TITLE
Updated README with how to upgrade ansible

### PR DESCRIPTION
**Pull request by tldavies**

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1: looks good to me!

**Comment by DavidjohnBlodgett** [comment]
@RackHD/corecommitters

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
@tldavies there's a small comment at the top of the readme at https://github.com/RackHD/on-imagebuilder/blob/master/README.md#requirements that says "Ansible (> 2.0) is installed (apt-get install ansible or pip install ansible)". Maybe change that to a ref link to your installation section instead?

**Comment by anhou** [comment]
:+1:  with @benbp 's comments

**Comment by tldavies** [comment]
@benbp changes made

**Comment by benbp** [comment]
@tldavies one last pedantic nit then I'll shut up forever: change "Ansible Installations Documents" to "Ansible Installation Documents"

**Comment by heckj** [comment]
no way @benbp will shut up forever

**Comment by tldavies** [comment]
@benbp I fixed it. And I dont believe you will ever shut up.

**Comment by benbp** [comment]
I'm shutting up, and merging.

**Comment by tldavies** [comment]
@benbp for now

**Pull request merged**
