### PR TITLE
initial port of ipxebuilder ansible role

### PR DESCRIPTION
**Pull request by heckj**
# WIP
- need to test this flow and make sure I didn't miss anything

porting older ansible role into structure used by on-imagebuilder for invocation locally on an ubuntu-based linux host

### CODE REVIEW

**Comment by benbp** [comment]
Looks good, if we include it in all.yml, is the though to also remove it from on-tftp source control then (I assume yes)?

**Comment by heckj** [comment]
yeah - that was the idea. In the docs in section 6 (http://rackhd.readthedocs.org/en/latest/packaging_and_deployment.html#upgrading-the-code), we have instructions to install on-static-common (as well as the various application deb packages) which is basically what this repository is built to generate from scratch. I don't know if we want to ammend this setup to make that package (it's freakin' huge), or amend the instructions to be more specific about what files need to go where, copying them in from the results that this creates.

**Comment by benbp** [comment]
:+1:

**Comment by heckj** [comment]
@benbp @jlongever this one's been tested and verified to build the right stuff. Leaves the output in /tmp/on-imagebuilder/ipxe to follow the general pattern that Ben set up with the overlays

**Comment by jlongever** [comment]
@heckj I'll be sure to include ipxe images in the bintray deploy files.   There may be other updates to the microkernel portion to make travis-ci happy.  Still working through those issues.

**Comment by heckj** [comment]
grazie @jlongever

**Comment by jlongever** [comment]
:+1:

**Comment by jlongever** [comment]
@heckj @benbp I just noticed the UEFI build steps weren't included.
@keedya did you ever include the ansible task for monorail-efi32-snponly.efi and monorail-efi64-snponly.efi?

**Comment by heckj** [comment]
@jlongever afraid I didn't see the UEFI build pieces in my edition of on-ansible (the original repo) - not sure what those steps are/were. @keedya if you have that stashed somewhere, would you consider adding as a follow on pull request to this setup so we have the right stuff built to support UEFI booting?

**Comment by keedya** [comment]
Sure will do!

**Comment by keedya** [comment]
Building ipxe.efi for 32 bit machine fails if I add COMBOOT syslinux support
@benbp @heckj

**Comment by heckj** [comment]
@keedya we may not need it any longer, was originally added to support hand-made DOS disks so we could boot and run the seriously ghetto tools that some HW vendors provided in DOS only

**Comment by jlongever** [comment]
@keedya did you remove the COM define from the copied config header?  Otherwise EFI build will fail.

**Comment by keedya** [comment]
I can succesfully build it if I remove COMBOOT from general.h.
My question here is if we still want to build it this way?

**Comment by jlongever** [comment]
Based on @heckj comment probably not.   But just have your ansible task sed that line out.

**Pull request merged**
