### PR TITLE
update readme for ansible version and overlay

### PR DESCRIPTION
**Pull request by anhou**
@RackHD/corecommitters @PengTian0 @iceiilin

### CODE REVIEW

**Comment by benbp** [comment]
@anhou what's the issue with 2.1? You get an error?

**Comment by anhou** [comment]
@benbp travis CI error is the error with version 2.1.0.0. travis CI always to download the latest ansible version, I've locked the version to 2.0.2.0 to make travisCI pass in PR  https://github.com/RackHD/on-imagebuilder/pull/42

log errors:
TASK [setup] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [/tmp/on-imagebuilder/initrd_build_env/rootfs]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_G43rs8/ansible_module_setup.py\", line 127, in <module>\n    main()\n  File \"/tmp/ansible_G43rs8/ansible_module_setup.py\", line 119, in main\n    data = get_all_facts(module)\n  File \"/tmp/ansible_G43rs8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3177, in get_all_facts\n  File \"/tmp/ansible_G43rs8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3123, in ansible_facts\n  File \"/tmp/ansible_G43rs8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 919, in populate\n  File \"/tmp/ansible_G43rs8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 107, in wrapper\n  File \"/tmp/ansible_G43rs8/ansible_modlib.zip/ansible/module_utils/facts.py\", line 1142, in get_mount_facts\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by anhou** [comment]
@benbp TravisCI pass  with rebase merged https://github.com/RackHD/on-imagebuilder/pull/42 this time :)

**Comment by yyscamper** [comment]
:+1:

**Comment by iceiilin** [comment]
:+1:

**Pull request merged**
