### PR TITLE
Add udev package to fix  get_driverid task and start lldp daemon 

### PR DESCRIPTION
**Pull request by keedya**

### CODE REVIEW

**Comment by keedya** [comment]
depends on: https://github.com/RackHD/on-imagebuilder/pull/68

**Comment by keedya** [comment]
@RackHD/corecommitters @brianparry @geoff-reid @tannoa2 @uppalk1

**Comment by yyscamper** [comment]
@keedya : Could you give some more info on the problem you encountered with get_driveId? So that we all are aware of such problem in future.

Add @pengz1 as he is the owner of get_driveId script.

**Review by yyscamper — APPROVED** [review]

**Comment by keedya** [comment]
@yyscamper , the dockerized image didn't have access to /dev/ (it is unsafe to mount /dev/ to a container but get drive_id relies on it and on udev to build the data). @pengz1 is there  another way to generate this data like using lshw cmd?
Docker image works with the current discovery. We can make changes in the future if we decide to replace the drivId script

**Comment by anhou** [comment]
@keedya  maybe it's a 'have-to' to let the device related command in docker have the privilege to access /dev/* devices? especially some old tools access /dev/* devices as a default path.

**Comment by yyscamper** [comment]
Thanks @keedya

**Comment by pengz1** [comment]
@keedya, lshw does include all PCI info, but it is difficult to pick and parser drive info. Also I am not sure if I can find enough info like serial number, wwn.

**Pull request merged**
