### PR TITLE
update version of initramfs-tools to 0.103ubuntu4.4 and apt-utils to …

### PR DESCRIPTION
**Pull request by PengTian0**
update initramfs-tools for dell raid overlay and raid overlay.
update apt-utils for raid overlay.

### CODE REVIEW

**Comment by yyscamper** [comment]
@heckj @benbp @anhou @brianparry @zyoung51 @jlongever : 
Do you have any idea about how to resolve this version change once for all? As I see a lot PR for on-imagebuilder is just to update the package version.

For the Ansible document, the version supports wildcards:
[Ansible-apt-module](http://docs.ansible.com/ansible/apt_module.html)

```
A package name, like foo, or package specifier with version, like foo=1.0. Name wildcards (fnmatch) like apt* and version wildcards like foo=1.0* are also supported.
```

My suggestion is to change the version string to use wildcards, for example. Do you have any insight on the side-effect?

```
- { package: "initramfs-tools", version: "0.103ubuntu*"}
```

**Comment by PengTian0** [comment]
The wildcards works well.
If we use wildcards , we should apply it to all the apt package versions, right?

**Comment by heckj** [comment]
👍

**Comment by benbp** [comment]
We could also do a minor update to the playbooks to not require pinned versions @yyscamper, which I would be fine with (this has turned out to be more trouble than it's worth IMO). Wild card versions seems like a great solution as well.

👍

**Pull request merged**
