### PR TITLE
Kernel bump3.19

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@RackHD/corecommitters @tldavies @VulpesArtificem @rolandpoulter  this is one of a 2 part PR (also in https://github.com/RackHD/on-tasks/pull/148) to support the new micro kernel.

### CODE REVIEW

**Comment by benbp** [comment]
Please don't merge until there is a packer update (see https://github.com/RackHD/on-tasks/pull/148#issuecomment-202614490).

**Comment by anhou** [comment]
:+1:

**Comment by stuart-stanley** [comment]
So it looks like there needs to be near simultaneous merges in three places(?) to not break? You may want to send out a (large text) heads up in at least the slack-channel, since if anyone manages to miss picking one of those up in their environment, they will be a wee bit confused, I think.  

(Actually it's four places, since I'll also need to update the OnRack on-static-common, since it requires version tracking over time and bintray is merely "latest" alas. So please let ME know when the merge is about to fire :) )

**Comment by benbp** [comment]
@stuart-stanley yep, we might inadvertently break some people :/

Also, the name change of the overlay to include the kernel version should hopefully help with some of your issues since it's easier to tell what pairs with what (even though they should all work with each other).

**Comment by DavidjohnBlodgett** [comment]
@stuart-stanley understood, I'll work on composing a slack / email heads up.

**Comment by stuart-stanley** [comment]
So, is there anything happening with this?

**Comment by benbp** [comment]
@stuart-stanley I think so? There was some debate on a dependent PR, but I think that's resolved. @DavidjohnBlodgett ?

**Comment by stuart-stanley** [comment]
Sorry, looking back, that appeared really terse :). Real question, but please take the tone as more curious!

**Comment by DavidjohnBlodgett** [comment]
@stuart-stanley @benbp lol no worries, I honestly got distracted by other tasks and really did not full follow up on pushing this through after I made a refactor to on-tasks based on feedback. At this time I think we are good to go, to merge all these... just need to send out that warning

**Comment by benbp** [comment]
👍

**Pull request merged**
