### PR TITLE
Add sysnlinux bootloader support

### PR DESCRIPTION
**Pull request by anhou**
undionly.kpxe from ipxe is not the original gPXE's undionly.kkpxe file which has been validated for installing ESXi on multiple platforms, correct it here. This will fix the chainload failure issue when installing ESXi OS

related PR:
https://github.com/RackHD/RackHD/pull/70
https://github.com/RackHD/on-http/pull/91

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1

**Comment by anhou** [comment]
@benbp https://github.com/RackHD/on-tasks/pulls has been merged, I'm not sure why travis-ci still use 1:6.6p1-2ubuntu2.3 which lead to failure when re-building ?

**Comment by benbp** [comment]
@andrewhou because my PR got reverted temporarily for the 1.1 release effort.

**Comment by anhou** [comment]
@benbp I saw that only https://github.com/RackHD/on-tasks/pull/109 was reverted, https://github.com/RackHD/on-imagebuilder/pull/19 is still there.  and about when https://github.com/RackHD/on-tasks/pull/109 could be back?  otherwise this PR travisCI cannot pass and cannot have a building, @heckj mentioned this PR in slack that need this PR to do a packer build.

**Comment by DavidjohnBlodgett** [comment]
@heckj @benbp is this PR even valid anymore? It looks like ben made a change in a different PR that fixes the build issue.

**Comment by DavidjohnBlodgett** [comment]
@benbp @heckj @anhou so it was brought up in scrum that you may want to rebase this PR to get our fix~

**Comment by benbp** [comment]
@DavidjohnBlodgett yes this PR is still valid.

**Comment by heckj** [comment]
I just tried the packer build, and my error has been resolved - so not sure we need this any longer... At least, I don't have a dependency on it...

**Comment by benbp** [comment]
@heckj isn't this a feature for syslinux though? Don't we need that?

**Comment by heckj** [comment]
yeah, we totally do

**Comment by anhou** [comment]
@benbp the travisCI pass after adding installing e2fslibs-dev package for syslinux and also need to base on the PR of resolving dependences  https://github.com/RackHD/on-imagebuilder/pull/24.
I'll merge this PR

**Pull request merged**
