### PR TITLE
add gdisk that contains sgdisk to installed packages for overlay

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@RackHD/corecommitters 

this will add "gdisk" to our overlay dependencies, this package contains the "sgdisk" tool requested by this issue: https://github.com/RackHD/RackHD/issues/373

-DJ

### CODE REVIEW

**Comment by benbp** [comment]
Wouldn't it make more sense to add this to something like a "decommission overlay" rather than the discovery overlay, since it's not used at all by discovery, and the decommission task doesn't use any tools other than sgdisk (like lspci, etc.)

**Comment by heckj** [comment]
@benbp Do we have a separate decommission overlay that we trigger, or does that just use the single "default" overlay?

**Comment by DavidjohnBlodgett** [comment]
I thought it was using the same overlay for both~ if I'm mistaken, I'll move the change, but not really sure if there is value in partitioning this into two overlays.

**Comment by DavidjohnBlodgett** [comment]
well, I guess I could walk back my comment... if we're concerned about the overall size of the base discovery kernel...

**Comment by heckj** [comment]
👍

**Comment by yyscamper** [comment]
Echo @benbp 's comment, take the secure erase for example, we used a different name of overlay rather than the default one. https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/secure-erase-drive-graph.js#L10

**Comment by DavidjohnBlodgett** [comment]
@benbp @yyscamper understood, I'll circle back and make these changes... getting side barred due to a fire drill... but I'll get this up asap.

**Comment by DavidjohnBlodgett** [comment]
@yyscamper @benbp @heckj  hey guys, sorry its taken me so long to circle back to this... vacation and sickness all hit at once... anyway, would either of you have any objections with me slipping the sgdisk dependency into the secure erase? or is your point that we SHOULD have a "decommission" overlay and I should just build that out now with a new oem script~ (I did not see anything in the oem script that was an actual decom script... like joe asked)

**Review by yyscamper — APPROVED** [review]

**Comment by DavidjohnBlodgett** [comment]
@RackHD/corecommitters this should be merge ready.

**Review by rolandpoulter — APPROVED** [review]

**Pull request merged**
