### PR TITLE
Add apache 2.0 license

### PR DESCRIPTION
**Pull request by benbp**
@RackHD/corecommitters @heckj

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
@benbp it seems to needs a rebase to let travisci pass, it looks like the travis ci failure caused by 'curl' version could be resolved by @heckj 's fix

commit 8fdd07945410515c46add5d98cf87a04720b7127
Author: Joe Heck heckj@mac.com
Date:   Wed Jul 20 12:09:29 2016 -0700

```
updating upstream version of curl

 - version 7.35.0-1ubuntu2.6 replaced with 7.35.0-1ubuntu2.7
```

**Comment by benbp** [comment]
@anhou done

**Comment by anhou** [comment]
:+1:

**Pull request merged**
