### PR TITLE
Removing 10 sec sleep since we moved to atomic lookup

### PR DESCRIPTION
**Pull request by tldavies**
Dont merge until https://github.com/RackHD/RackHD/issues/121 has been fixed.

### CODE REVIEW

**Comment by benbp** [comment]
This requires https://github.com/RackHD/on-dhcp-proxy/pull/28

FYI @keedya and @miramm

**Comment by benbp** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by tldavies** [comment]
@RackHD/corecommitters please merge

**Pull request merged**
